name: Auto Merge Pull Requests
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash # Change to merge or rebase as required
          MERGE_COMMIT_MESSAGE: "Automated merge of pull request #${{ github.event.pull_request.number }}"
